2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_setup.py:_flush():76] Configure stats pid to 138581
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_setup.py:_flush():76] Loading settings from /home/iscilab/.config/wandb/settings
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_setup.py:_flush():76] Loading settings from /data2/douyoungk/train/wandb/settings
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'lit_module.py', 'program_abspath': '/data2/douyoungk/train/lit_module.py', 'program': '/data2/douyoungk/train/lit_module.py'}
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_init.py:_log_setup():524] Logging user logs to ./wandb/run-20250711_230436-ll5hlfql/logs/debug.log
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_init.py:_log_setup():525] Logging internal logs to ./wandb/run-20250711_230436-ll5hlfql/logs/debug-internal.log
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_init.py:init():564] calling init triggers
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_init.py:init():614] starting backend
2025-07-11 23:04:36,428 INFO    MainThread:138581 [wandb_init.py:init():618] setting up manager
2025-07-11 23:04:36,428 INFO    MainThread:138581 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-11 23:04:36,429 INFO    MainThread:138581 [wandb_init.py:init():624] backend started and connected
2025-07-11 23:04:36,430 INFO    MainThread:138581 [wandb_init.py:init():716] updated telemetry
2025-07-11 23:04:36,433 INFO    MainThread:138581 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-07-11 23:04:37,272 INFO    MainThread:138581 [wandb_run.py:_on_init():2254] communicating current version
2025-07-11 23:04:37,300 INFO    MainThread:138581 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.21.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-07-11 23:04:37,300 INFO    MainThread:138581 [wandb_init.py:init():800] starting run threads in backend
2025-07-11 23:04:37,881 INFO    MainThread:138581 [wandb_run.py:_console_start():2233] atexit reg
2025-07-11 23:04:37,881 INFO    MainThread:138581 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2025-07-11 23:04:37,881 INFO    MainThread:138581 [wandb_run.py:_redirect():2153] Wrapping output streams.
2025-07-11 23:04:37,882 INFO    MainThread:138581 [wandb_run.py:_redirect():2178] Redirects installed.
2025-07-11 23:04:37,882 INFO    MainThread:138581 [wandb_init.py:init():841] run started, returning control to user process
2025-07-11 23:04:37,956 INFO    MainThread:138581 [wandb_run.py:_config_callback():1342] config_cb None None {'lat_size': 204, 'lon_size': 320, 'sog_size': 30, 'cog_size': 36, 'n_lat_embd': 256, 'n_lon_embd': 256, 'n_sog_embd': 128, 'n_cog_embd': 128, 'd_model': 768, 'n_head': 8, 'num_layers_enc': 3, 'num_layers_fus': 3, 'num_layers_dec': 3, 'dim_feedforward': 512, 'dropout': 0.1, 'max_len': 120, 'lr': 0.0001}
2025-07-11 23:05:48,275 INFO    MainThread:138581 [wandb_run.py:_config_callback():1342] config_cb None None {'lat_size': 204, 'lon_size': 320, 'sog_size': 30, 'cog_size': 36, 'n_lat_embd': 256, 'n_lon_embd': 256, 'n_sog_embd': 128, 'n_cog_embd': 128, 'd_model': 768, 'n_head': 8, 'num_layers_enc': 3, 'num_layers_fus': 3, 'num_layers_dec': 3, 'dim_feedforward': 512, 'dropout': 0.1, 'max_len': 120, 'lr': 0.0001}
2025-07-11 23:05:55,174 WARNING MsgRouterThr:138581 [router.py:message_loop():77] message_loop has been closed
